### ISSUE TITLE
0.3.3 release tarball contains an unexpectedly named directory

### ISSUE THREAD

**Issue by rathann** [MDAnalysis/GridDataFormats#34]
**0.3.2** contained `GridDataFormats-0.3.2`, but **0.3.3** contains `GridDataFormats-release-0.3.3`, which is unexpected and breaks my packaging workflow. Please redo the tarball or release an update with a directory name in line with previous releases.

**Comment by orbeckst** [comment]
Can you please tell me to which tarball you are referring?

- The Python [source distribution on pypi](https://pypi.python.or/pypi/GridDataFormats#downloads) *GridDataFormats-0.3.3.tar.gz*  gives me `GridDataFormats-0.3.3/`:
   ```
   $ curl https://pypi.python.org/packages/1b/5d/768a606951c2868b5fcf446c8118557946fa0763ed70adfb429f18c017e0/GridDataFormats-0.3.3.tar.gz#md5=5c83d3bdd421eebcee10111942c5a21f 2>/dev/null | tar tvf - | head -n 1
   drwxr-xr-x  0 oliver staff       0 May 13  2016 GridDataFormats-0.3.3/
   ```
   The ones on pypi are generated with `python setup.py sdist`.
- The [GitHub repo tarballs](https://github.com/MDAnalysis/GridDataFormats/releases) are automatically generated by GitHub follow the pattern `GridDataFormats-release-0.3.3/`
   ```
   $ curl -L https://github.com/MDAnalysis/GridDataFormats/archive/release-0.3.3.tar.gz 2>/dev/null | tar tvf - | head -n 1
   drwxrwxr-x  0 root   root        0 May 13  2016 GridDataFormats-release-0.3.3/
   ```
   but I wouldn't use them as a the basis for packaging because they are repo snapshots.

**Comment by rathann** [comment]
I'm referring to the pypi tarball:
https://pypi.python.org/packages/source/G/GridDataFormats/GridDataFormats-0.3.3.tar.gz
```
$ sha256sum GridDataFormats-0.3.3.tar.gz 
f58a06c94628b7dff907fd81759b002bf122ce35536dd975a21118901849a677  GridDataFormats-0.3.3.tar.gz
$ gzip -dc GridDataFormats-0.3.3.tar.gz |tar -tf - |head
GridDataFormats-release-0.3.3/
GridDataFormats-release-0.3.3/.gitignore
GridDataFormats-release-0.3.3/.nojekyll
GridDataFormats-release-0.3.3/.travis.yml
GridDataFormats-release-0.3.3/AUTHORS
...
```

**Comment by kain88-de** [comment]
@rathann no problem. It's nice to know that people are using our packages and find them useful enough to package them for distributions. Thanks for that.
